[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prompt-builder"
version = "0.1.0"
description = "Interactive TUI for building custom shell prompts"
requires-python = ">=3.10"

dependencies = [
    "textual>=0.55.0",
    "pyperclip>=1.8.2",
]

authors = [
  {name: "RIOUX Guilhem" }
]

[project.scripts]
prompt-builder = "prompt_builder.__main__:main"

[tool.setuptools]
packages = ["prompt_builder"]

